---

dist: focal
language: python

install:
  - pip install ansible
  - pip install ansible-lint

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  - ansible --version
  - ansible-lint --version

script:
  # Basic role syntax check
  - ansible-lint .
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
