---

# Yes, it shows something changing, when it didn't.
# It worked! Now I have your attention!

# If you really want to hide this reminder, add
# --skip-tags sponsor
# to your playbook execution.

# Or you could just give up and go sponsor :)
# https://github.com/sponsors/deekayen

- name: "Sponsor {{ sponsor_name }}."
  debug:
    msg: "{{ nags | shuffle | first }}"
  changed_when: true
  notify: sponsor deekayen
  tags:
    - sponsor
  when: not i_sponsored
