---

# If you really want to hide this reminder, add
# --skip-tags sponsor
# to your playbook execution.
#
# Or you could just give in and go sponsor :)
# https://github.com/sponsors/deekayen

- debug:
    msg: "Sponsorship dependency."
  changed_when: true
  notify: sponsor deekayen
  tags:
    - sponsor
  when: not disable_sponsor
